-- This is a placeholder; actual migration generated by drizzle-kit
-- Add search extensions and indexes manually if needed
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

-- Add generated column to listings after table creation
ALTER TABLE listings ADD COLUMN search_vector tsvector 
GENERATED ALWAYS AS (
  setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
  setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
  setweight(to_tsvector('english', coalesce(location, '')), 'C')
) STORED;

CREATE INDEX IDX_listing_search_vector ON listings USING GIN (search_vector);
CREATE INDEX IDX_listing_title_trgm ON listings USING GIN (title gin_trgm_ops);
CREATE INDEX IDX_listing_description_trgm ON listings USING GIN (description gin_trgm_ops);
CREATE INDEX IDX_listing_location_trgm ON listings USING GIN (location gin_trgm_ops);
CREATE INDEX IDX_listing_composite_search ON listings USING GIN (price, location, search_vector);
CREATE INDEX IDX_listing_price_created ON listings (price, createdAt DESC);
CREATE INDEX IDX_listing_location_price ON listings (location, price);
CREATE INDEX IDX_listing_created_price ON listings (createdAt DESC, price);